### ISSUE TITLE
[BUG]: Welcome message not centered

### ISSUE THREAD

**Issue by guptasajal411** [mayukhpankaj/Hacktoberfest-Organiser-Page#1]
I noticed that the `<h1>` tag is inside the Bootstrap `text-center` classed div, but still not centered - 
![image](https://user-images.githubusercontent.com/70312106/135595999-a505e45b-9e51-41b7-8578-605ea4b848e8.png)
![image](https://user-images.githubusercontent.com/70312106/135596005-9fe2060c-5fb4-4f06-b398-96990da0062a.png)

Can you assign me this issue, I can work on this 👍

**Comment by mayukhpankaj** [comment]
Yeah sure !

**Comment by Garima-7** [comment]
Please asign this issue to me.

**Comment by mayukhpankaj** [comment]
closed
