### ISSUE TITLE
Navbar alignment 

### ISSUE THREAD

**Issue by aniket-choudhary2002** [mayukhpankaj/Hacktoberfest-Organiser-Page#6]
I want to make the logo to the left most side so it will look more aesthetic
![WhatsApp Image 2021-10-03 at 9 27 00 PM](https://user-images.githubusercontent.com/73525519/135764201-4fbcefb8-7f31-4826-bff4-44117368672a.jpeg)
.

**Comment by MariamChowdhury** [comment]
Hi, I can fix this. Can you assign me this issue?

**Comment by MayankHora** [comment]
Hi, I can fix this. Can you assign me this issue?

**Comment by nayan2306** [comment]
Hi can you assigned me I will fix it

**Comment by mayukhpankaj** [comment]
Sorry, But I did this on purpose.
